---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: fruits
  labels:
    app: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: 847322629192.dkr.ecr.ap-northeast-2.amazonaws.com/react-frontend-dualcidr:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  namespace: fruits
spec:
  selector:
    app: react-frontend
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: react-frontend
  namespace: fruits
  labels:
    app: react-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: app.pub.tbiz-atcl.net
    http:
      paths:
      - path: /
        backend:
          serviceName: react-frontend
          servicePort: 3000
